name: Deploy GH Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: REPO_NAME=${{ secrets.REPO_NAME }} WP_URL=${{ secrets.WP_URL }} npm run build && npm run export
      - name: Add .nojekyll
        run: echo > out/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
